[setup]
nixPkgs = ["...", "gulp", "pm2", "git"]
aptPkgs = ['curl', 'wget', 'libgeoip-dev', 'gnupg', 'ffmpeg', 'imagemagick', 'graphicsmagick', 'fontconfig', 'fonts-dejavu']

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks-reset.toml"
cmd = 'npm run setup'
# dockerfilePath = "docker/jschan/Dockerfile"

[install]
cmd = "npm install --production"

[start]
startCommand = 'npm run reset'

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
